LunarCore.m
const int minYear
const int maxYear
const int weekStart
NSString* NSString* text
获得不为空的字符串 text text text
int springFestival[][211][][211]
int lunarInfo[][210][][210]
1890 - 2100 年的农历数据 数据格式：[0,2,9,21936] [闰月所在月，0为没有闰月; *正月初一对应公历月; *正月初一对应公历日; *农历每月的天数的数组（需转换为二进制,得到每月大小，0=小月(29日),1=大月(30日)）;]
int termInfo[][]
二十四节气数据，节气点时间（单位是分钟） 从0小寒起算
int solarDaysOfMonth[][]
static NSString* i18n(NSString *key)
获得本地化的字符串 这里 app 可以自行实现 text key 本地化字符串
LCMemoryCache* memoryCache()
NSTimeZone* timeZone()
Referenced by NSDateFormatter(Make)::dateFormatterWithFormat:timeZone:locale:, NSDateFormatter(Make)::dateFormatterWithDateStyle:timeZone:, NSDateFormatter(Make)::dateFormatterWithTimeStyle:timeZone:.
NSMutableArray* createMonthData(int year, int month, int len, int start)
以年月和长度构造一个日历 year 年 month 月 len 参数 start 开始日期 整月日历
NSDictionary* errorCode()
NSString* formatDay(int month, int day)
格式化日期 month 月份 day 日期 格式化后的日期
NSDictionary* lunarCalendarData()
NSMutableDictionary* worktime()
NSDictionary* solarFestival()
NSDictionary* lunarFestival()
NSDictionary* weekFestival()
NSDate* Date(int year, int month, int day)
构造 NSDate year 年 month 月 day 日 NSDate
NSDate* NewDate(int year, int month, int day)
构造 NSDate year 年 month 月 day 日 NSDate
NSString* getWeekFestival(int year, int month, int day)
获得以周为单位的节日 year 年 month 月 day 日 节日
int getLunarLeapYear(int year)
判断农历年闰月数 year 农历年 闰月数 （月份从1开始）
NSArray* toString(int num)
NSMutableDictionary* getLunarYearDays(int year)
获取农历年份一年的每月的天数及一年的总天数 year 农历年 总天数
NSMutableArray* getLunarDateByBetween(int year, int between)
通过间隔天数查找农历日期 year 农历年 between 间隔天数 农历日期
int getDaysBetweenSolar(int year, int month, int day, int year1, int month1, int day1)
两个公历日期之间的天数 year 年 month 月 day 日 year1 年2 month1 月2 day1 日2 间隔天数
NSMutableArray* getLunarByBetween(int year, int month, int day)
根据距离正月初一的天数计算农历日期 year 公历年 month 月 day 日 农历日期
NSTimeInterval UTC(int year, int month, int day, int hour, int min, int sec)
某年的第n个节气为几日 由于农历24节气交节时刻采用近似算法，可能存在少量误差(30分钟内) 31556925974.7为地球公转周期，是毫秒 1890年的正小寒点：01-05 16:02:31，1890年为基准点 y 公历年 n 第几个节气，从0小寒起算
int getDay(NSDate *date)
根据 NSDate 获得天 date date 天
int getTerm(int y, int n)
NSMutableDictionary* getYearTerm(int year)
获取公历年一年的二十四节气 year 年 日期: 节气名
NSString* getYearZodiac(int year)
获得生肖 year 年 生肖
NSString* cyclical(long num)
计算天干地支 num 60进制中的位置(把60个天干地支，当成一个60进制的数) 天干地支
NSString* getLunarYearName(int year, int offset)
获取干支纪年 year 干支所在年 offset 偏移量，默认为0，便于查询一个年跨两个干支纪年（以立春为分界线） 干支纪年
BOOL isLeapYear(int year)
判断公历年是否是闰年 year 公历年 是否是闰年
Referenced by NSDate(Utils)::getDayCountForMonth:month:.
int getSolarMonthDays(int year, int month)
获取公历月份的天数 year 公历年 month 公历月 该月天数
NSMutableDictionary* formatDate(int year, int month, int day)
统一日期输入参数（输入月份从1开始，内部月份统一从0开始） year 年 month 月 day 日 格式化后的日期
BOOL isNewLunarYear(int _year, int _month, int _day)
判断是否处于农历新年 _year 阳历年 _month 阳历月 _day 阳历日 YES 表示处于农历新年
NSMutableDictionary* solarToLunar(int _year, int _month, int _day)
公历转换成农历 _year 公历年 _month 公历月 _day 公历日 农历年月日
NSMutableDictionary* solarCalendar(int _year, int _month)
某月公历 _year 公历年 _month 公历月 公历
NSMutableDictionary* calendar(int _year, int _month)
获取指定年月的日历数据 _year 公历年 _month 公历月 该月日历
Referenced by NSDate(CupertinoYankee)::beginningOfDay, NSDate(CupertinoYankee)::endOfDay, NSDate(CupertinoYankee)::beginningOfWeek, NSDate(CupertinoYankee)::endOfWeek, NSDate(CupertinoYankee)::beginningOfMonth, NSDate(CupertinoYankee)::endOfMonth, NSDate(CupertinoYankee)::beginningOfYear, NSDate(CupertinoYankee)::endOfYear, NSDate(Extension)::day:, NSDate(Extension)::month:, NSDate(Extension)::year:, NSDate(Extension)::hour:, NSDate(Extension)::minute:, NSDate(Extension)::second:, NSDate(Extension)::dateAfterDate:day:, NSDate(Extension)::dateAfterDate:month:, NSDate(Extension)::daysAgo:, NSDate(Extension)::isSameDay:, NSDate(Formatter)::dateWithSecondsFromNow:, NSDate(Formatter)::dateWithYear:month:day:, NSDate(TimeAgo)::dateTimeAgo, NSDate(TimeAgo)::dateTimeUntilNow, NSDate(Utils)::isSameDay:, NSDate(XDCommonLib)::weekday, NSDate(XDCommonLib)::isSameDay:, NSDate(XDCommonLib)::monthsBetweenDate:, NSDate(XDCommonLib)::dateInformationWithTimeZone:, NSDate(XDCommonLib)::dateFromDateInformation:timeZone:, NSDate(XDCommonLib)::shortDate.